# Numpy入门作业

In [ ]:
import numpy as np

### 作业1：

1. 生成一个3行5列的数组，元素值从1到15排列  
2. 取出其中的第1行，第3列元素  
3. 取出其中的第2行到最后一行  
4. 取出其中的第1行到第2行，第1列到最后一列  
5. 取出其中的第0行和第2行，第三列  

In [17]:
# 作业1代码
import numpy as np
x = np.arange(1, 16)
y = x.reshape(3, 5)
# 1
print(y)
# 2
print(y[1][3])
# 3
print(y[2:])
# 4
print(y[1:3, 1:])
# 5
# print(y[0:3:2, 3])
print(y[[0,2],3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
9
[[11 12 13 14 15]]
[[ 7  8  9 10]
 [12 13 14 15]]
[ 4 14]
[ 4 14]


## 作业2：  

给出一组学生姓名，和他们对应的成绩，存储在下方数组中。请计算以下问题：  
找出不及格的学生姓名（提示：使用布尔型索引）  
找出最高分、最低分，平均分数  
将数值成绩转化成字母成绩，大于等于90分为A， 70-89分为B，小于70分为C  

In [5]:
names = np.array(["Xiao Ming","Xiao Zhang","Xiao Gang","Xiao Hong","Xiao Pang","Xiao Wu","Xiao Dai",
                  "Xiao Qian","Xiao Fan","Xiao Wang"])
scores = np.array([ 91,  68,  84,  55,  95,  81,  67,  82,  86,  78])

In [32]:
# 作业2代码
import numpy as np
# 1
flag = scores[:] < 60
print(names[flag])
# 2
print(np.amax(scores))
print(np.amin(scores))
print(np.mean(scores))
# 3
x = np.where(scores < 70, 'C', np.where(scores > 90, 'A', 'B'))
print(x)

['Xiao Hong']
95
55
78.7
['A' 'C' 'B' 'C' 'A' 'B' 'C' 'B' 'B' 'B']
